import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import '../../assets/globals.css';
import tw from 'tailwind-styled-components';

const robotoMono = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
};

const Body = tw.body`text-black py-36`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Body className={robotoMono.className}>{children}</Body>
    </html>
  );
}
